version: '3'
services:
  db:
    image: postgres
    container_name: siaga-db
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_DB: '${DB_NAME}'
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    name: siaga-db-data
